version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: banking_sqlserver
    environment:
      SA_PASSWORD: "BankingDB@2024"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
#    healthcheck:
#      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "BankingDB@2024" -Q "SELECT 1" || exit 1

  app:
    build: ./backend
    container_name: banking_app
    ports:
      - "8000:8000"
    environment:
      DB_SERVER: sqlserver
      DB_NAME: PractiseBanking
      DB_USER: sa
      DB_PASSWORD: "BankingDB@2024"
    depends_on:
      - sqlserver
#      sqlserver:
#        condition: service_healthy
    volumes:
      - ./backend:/app

volumes:
  sqlserver_data: